### ISSUE TITLE
Upstream to neovim?

### ISSUE THREAD

**Issue by dundargoc** [nanotee/luv-vimdocs#1]
Hey! This looks very promising and I was wondering if neovim could use this and include this into neovim core? If you'd like to read more and share your thoughts: https://github.com/neovim/neovim/pull/19663

**Comment by nanotee** [comment]
Sure, I'd be happy if it were included! The luv repository is licensed under the Apache license, not sure if/how that affects inclusion in Neovim

**Comment by dundargoc** [comment]
Neovim is under apache too I think. Justin will have to take a look at the licensing bit, I'm just here to scout the texts :).

OK, thank you!
