### ISSUE TITLE
Syncing with up- and downstream

### ISSUE THREAD

**Issue by clason** [nanotee/luv-vimdocs#2]
With your kind permission (thank you! ❤️ ), Neovim now bundles these docs as https://github.com/neovim/neovim/blob/master/runtime/doc/luvref.txt, with some changes I made for integration with Nvim docs (taglinks, syntax highlighting for examples). This raises two questions:

1. Do you want to continue maintaining this repo? Then I would make a PR with these changes.
2. There were some updates to the Luv documentation in the meantime, and we're looking into how to sync these with our docs. If the answer to Question 1 is "No" (as I suspect it is), can you share the conversion script or process? This would make syncing via `nvim -d` much easier.

**Comment by nanotee** [comment]
1. I'd rather not continue maintaining this repository if it's not too much of a maintenance burden for the Neovim project.
2. I didn't make a script, the conversion was entirely manual. I update the file by diffing the changes between the last commit it was based on and the tip of the master branch and then formatting the text with `gw`. The documentation usually doesn't change too much so it isn't that time consuming, if a bit tedious.

**Comment by clason** [comment]
Thank you! Then we shall do the same. As the docs have been backported to the stable branch (0.8.x), feel free to archive the repo and point people to `:h luvref`.

And thanks again for doing the work; this is a very helpful addition to the documentation!
